# Generated by Django 2.0.4 on 2018-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_hash',
            field=models.CharField(default='', max_length=30),
        ),
    ]
