# Generated by Django 2.0.4 on 2018-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_confirm_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirm_hash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
