# Generated by Django 2.0.4 on 2018-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180508_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
