# Generated by Django 2.0.4 on 2018-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpayments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
