# Generated by Django 2.0.4 on 2018-05-09 09:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180509_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
