# Generated by Django 2.0.4 on 2018-05-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpayments',
            options={'verbose_name_plural': 'Payments'},
        ),
    ]
